### ISSUE TITLE
Unhandled Exception - Adding a Field Value to Update

### ISSUE THREAD

**Issue by jamespolak2** [rappen/BulkDataUpdater#227]
I am getting an unhandled exception when adding a field to update using the latest version of this tool. This happens regardless of what fetch xml query I use.

Steps to recreate:

1. Open the FetchXML Builder and create a query
2. Return the query to the Bulk Data Updater
3. The loading screen shows that it is loading the entity metadata (see 'Loading Screen Screenshot')

![Loading Screen](https://github.com/rappen/BulkDataUpdater/assets/114408776/b3d3ea95-59fc-4b87-afc6-faef843a8564)

5. Once it has finished loading, click add (see 'Steps to Recreate' screenshot)

![Steps to Recreate](https://github.com/rappen/BulkDataUpdater/assets/114408776/543a8cb5-2efe-4b67-aea2-3d832a6f3fae)

6. Error then appears (see 'Error' screenshot and the attached error details)

![Error](https://github.com/rappen/BulkDataUpdater/assets/114408776/2be79fe7-e691-47ff-8cff-d86cd29a1a1a)

[Error Details.txt](https://github.com/user-attachments/files/15872162/Error.Details.txt)

This seems to be happening regardless of whether the FetchXML Builder is being used to build and return the query, or if the query is added directly into the Bulk Data Updater

**Comment by rappen** [comment]
First: sorry about it takes tiiiime to load the cached metadata. But it's worth to wait for it.

I believe the error occurs since your query does not include any attributes (or use `all-attributes`) - the code wouldn't expect that that can happen.
I have a new commit regarding just this issue, will not error in this case in the next release. https://github.com/rappen/BulkDataUpdater/commit/fe3d4f70833a0b367121c4a3bd7810629b72792b

Can you check it if it still occurs these errors when you have a proper attributes in the FetchXML query?

**Comment by jamespolak2** [comment]
Yes, it works with the attributes 👍 Thanks!
